name: ECS Deploy1

on:
  push:
    branches:
      - main  # Change this if you want to trigger on different branches

jobs:
  deploy:
    name: Deploy to ECS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Use the Node.js version your project requires

      - name: Install NPM dependencies
        run: cp -rf ./assets/ react-client/src && cd react-client && npm install
      
      - name: Build
        run: cd react-client && npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1  # Replace with your AWS region if different

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push Docker image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: edp-people-picker  # Replace with your ECR repository name
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Copy necessary files
          cp -f ./package*.json scripts/
          cp -rf ./server/ scripts/server
          # cp -rf ./assets/ scripts/assets
          cp -rf ./react-client/dist scripts/client
          # Build the Docker image
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./scripts/.
          # Push the Docker image to ECR
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Update ECS service with new task definition
        env:
          CLUSTER_NAME: edp-cluster  # Replace with your ECS cluster name
          SERVICE_NAME: edp-service  # Replace with your ECS service name
          TASK_DEFINITION_NAME: edp-task  # Replace with your task definition family name
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: edp-people-picker  # Replace with your ECR repository name
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Fetch the current task definition
          CURRENT_TASK_DEFINITION_JSON=$(aws ecs describe-task-definition --task-definition $TASK_DEFINITION_NAME)

          # Update the task definition with the new image
          NEW_TASK_DEFINITION=$(echo $CURRENT_TASK_DEFINITION_JSON | jq --arg IMAGE "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" '.taskDefinition | .containerDefinitions[0].image=$IMAGE | del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .compatibilities, .registeredAt, .registeredBy)')

          # Register the new task definition
          NEW_TASK_DEF_ARN=$(aws ecs register-task-definition --cli-input-json "$NEW_TASK_DEFINITION" --query 'taskDefinition.taskDefinitionArn' --output text)

          # Update the ECS service to use the new task definition
          aws ecs update-service --cluster $CLUSTER_NAME --service $SERVICE_NAME --task-definition $NEW_TASK_DEF_ARN

      # New steps to output the public IP of the deployed ECS task
      - name: Wait for service to stabilize
        env:
          CLUSTER_NAME: edp-cluster
          SERVICE_NAME: edp-service
        run: |
          echo "Waiting for the ECS service to stabilize..."
          aws ecs wait services-stable --cluster $CLUSTER_NAME --services $SERVICE_NAME

      - name: Get public IP of the ECS task
        env:
          CLUSTER_NAME: edp-cluster
          SERVICE_NAME: edp-service
        run: |
          echo "Fetching the public IP of the ECS task..."
          # List tasks in the service
          TASK_ARN=$(aws ecs list-tasks --cluster $CLUSTER_NAME --service-name $SERVICE_NAME --query 'taskArns[0]' --output text)
          echo "Task ARN: $TASK_ARN"

          # Describe the task to get the public IP directly
          PUBLIC_IP=$(aws ecs describe-tasks --cluster $CLUSTER_NAME --tasks $TASK_ARN --query 'tasks[0].attachments[0].details[?name==`publicIPv4Address`].value' --output text)

          if [ "$PUBLIC_IP" = "None" ] || [ -z "$PUBLIC_IP" ]; then
            echo "Public IP not found in task details. Trying via ENI..."

            # Get the ENI ID
            ENI_ID=$(aws ecs describe-tasks --cluster $CLUSTER_NAME --tasks $TASK_ARN --query 'tasks[0].attachments[0].details[?name==`networkInterfaceId`].value' --output text)
            echo "ENI ID: $ENI_ID"

            # Get the public IP address from the ENI
            PUBLIC_IP=$(aws ec2 describe-network-interfaces --network-interface-ids $ENI_ID --query 'NetworkInterfaces[0].Association.PublicIp' --output text)
          fi

          echo "Public IP: $PUBLIC_IP"